# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindows(object):
    def setupUi(self, MainWindows):
        MainWindows.setObjectName("MainWindows")
        MainWindows.setWindowModality(QtCore.Qt.NonModal)
        MainWindows.resize(571, 395)
        MainWindows.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label = QtWidgets.QLabel(MainWindows)
        self.label.setGeometry(QtCore.QRect(210, 10, 231, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(MainWindows)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(MainWindows)
        self.label_3.setGeometry(QtCore.QRect(30, 150, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(MainWindows)
        self.label_5.setGeometry(QtCore.QRect(30, 200, 61, 16))
        self.label_5.setObjectName("label_5")
        self.txt_plain = QtWidgets.QTextEdit(MainWindows)
        self.txt_plain.setGeometry(QtCore.QRect(100, 60, 431, 71))
        self.txt_plain.setObjectName("txt_plain")
        self.txt_key = QtWidgets.QLineEdit(MainWindows)
        self.txt_key.setGeometry(QtCore.QRect(100, 150, 431, 20))
        self.txt_key.setObjectName("txt_key")
        self.txt_cipher = QtWidgets.QTextEdit(MainWindows)
        self.txt_cipher.setGeometry(QtCore.QRect(100, 190, 431, 71))
        self.txt_cipher.setObjectName("txt_cipher")
        self.btn_encrypt = QtWidgets.QPushButton(MainWindows)
        self.btn_encrypt.setGeometry(QtCore.QRect(120, 290, 75, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(MainWindows)
        self.btn_decrypt.setGeometry(QtCore.QRect(390, 290, 75, 23))
        self.btn_decrypt.setObjectName("btn_decrypt")

        self.retranslateUi(MainWindows)
        QtCore.QMetaObject.connectSlotsByName(MainWindows)

    def retranslateUi(self, MainWindows):
        _translate = QtCore.QCoreApplication.translate
        MainWindows.setWindowTitle(_translate("MainWindows", "CaesarCipher"))
        MainWindows.setToolTip(_translate("MainWindows", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("MainWindows", "<html><head/><body><p><span style=\" font-size:24pt;\">CEASAR CIPHER</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindows", "Plaintext"))
        self.label_3.setText(_translate("MainWindows", "Key"))
        self.label_5.setText(_translate("MainWindows", "CipherText"))
        self.btn_encrypt.setText(_translate("MainWindows", "Encrypt"))
        self.btn_decrypt.setText(_translate("MainWindows", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindows = QtWidgets.QWidget()
    ui = Ui_MainWindows()
    ui.setupUi(MainWindows)
    MainWindows.show()
    sys.exit(app.exec_())
